import java.awt.Color;
import java.awt.Graphics;
import java.io.IOException;
import java.text.DecimalFormat;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class BullyClient1 extends javax.swing.JFrame {

    private int myId;
    private int coordinatorId = -1;
    private java.util.List<Integer> clientesAtivos = new java.util.ArrayList<>();
    private boolean emEleicao = false;

    private volatile double volumeL = 1000.0;
    private volatile double pH = 5.0;
    private volatile double temperaturaC = 30.0;

    static double tempDriftPerSec = 0.02;
    static double acidezDriftPerSec = 0.001;

    static final double CAOH2_PER_G_ACID = 0.617;
    static final double WATER_TEMPERATURE = 15.0;

    static int riscoCounter = 0;
    static final int RISCO_LIMIT = 60;

    static boolean ledPHRed = false;
    static boolean ledTempRed = false;

    private static final DecimalFormat df3 = new DecimalFormat("0.000");
    private static final DecimalFormat df1 = new DecimalFormat("0.0");

    public BullyClient1() {
        initComponents();
    }

    public int getMyId() {
        return myId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lblVolumeVal = new javax.swing.JLabel();
        contadorLabel = new javax.swing.JLabel();
        lblPHVal = new javax.swing.JLabel();
        lblTempVal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        ledTemp = new javax.swing.JPanel();
        ledPH = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("localhost");

        jLabel1.setText("Server:");

        jLabel2.setText("Porta:");

        jTextField2.setText("6789");

        jButton1.setText("Conectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Desconectar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MaqBully - Client");

        jLabel3.setText("ID");

        jTextField3.setText("0");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton3.setText("Iniciar Eleição");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("User");

        jLabel6.setText("Coordenador:");

        jButton4.setText("Adicionar Agua");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Adicionar Cal");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lblVolumeVal.setBackground(new java.awt.Color(0, 0, 0));
        lblVolumeVal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblVolumeVal.setForeground(new java.awt.Color(0, 255, 51));
        lblVolumeVal.setText("Mosto");
        lblVolumeVal.setOpaque(true);

        contadorLabel.setBackground(new java.awt.Color(0, 0, 0));
        contadorLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        contadorLabel.setForeground(new java.awt.Color(0, 255, 51));
        contadorLabel.setText("Contador:");
        contadorLabel.setOpaque(true);

        lblPHVal.setBackground(new java.awt.Color(0, 0, 0));
        lblPHVal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPHVal.setForeground(new java.awt.Color(0, 255, 51));
        lblPHVal.setText("PH");
        lblPHVal.setOpaque(true);

        lblTempVal.setBackground(new java.awt.Color(0, 0, 0));
        lblTempVal.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTempVal.setForeground(new java.awt.Color(0, 255, 51));
        lblTempVal.setText("TEMP:");
        lblTempVal.setOpaque(true);

        logArea.setBackground(new java.awt.Color(0, 0, 0));
        logArea.setColumns(20);
        logArea.setForeground(new java.awt.Color(255, 255, 255));
        logArea.setRows(5);
        jScrollPane1.setViewportView(logArea);

        javax.swing.GroupLayout ledTempLayout = new javax.swing.GroupLayout(ledTemp);
        ledTemp.setLayout(ledTempLayout);
        ledTempLayout.setHorizontalGroup(
            ledTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        ledTempLayout.setVerticalGroup(
            ledTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ledPHLayout = new javax.swing.GroupLayout(ledPH);
        ledPH.setLayout(ledPHLayout);
        ledPHLayout.setHorizontalGroup(
            ledPHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        ledPHLayout.setVerticalGroup(
            ledPHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblVolumeVal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 143, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(lblPHVal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ledPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTempVal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ledTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)))
                                        .addComponent(contadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ledPH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPHVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(lblVolumeVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTempVal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ledTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String server = jTextField1.getText();
            int porta = Integer.parseInt(jTextField2.getText());
            int id = Integer.parseInt(jTextField3.getText());
            this.myId = id;
            tcpClient = new Bully_TCPClientMain(server, porta, this);
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    jLabel4.setText("User");
                    jLabel6.setText("Coordenador: Nenhum");
                }
            });
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            jTextField3.setEditable(false);
            tcpClient.writeMessage("JOIN|" + id + "|");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        closeConnection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fazerEleicao();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String s = javax.swing.JOptionPane.showInputDialog(this, "Litros de água a adicionar:", "Adicionar água", javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (s == null) {
            return;
        }
        try {
            double litros = Double.parseDouble(s.trim().replace(',', '.'));
            if (litros <= 0) {
                appendLog("Tentativa de adicionar água inválida: " + s);
                return;
            }
            tcpClient.writeMessage("ADD_WATER|" + String.format(java.util.Locale.US, "%.3f", litros) + "|");
            appendLog(String.format("%s Comando enviado: ADD_WATER %s L", timeNow(), df3.format(litros)));
        } catch (NumberFormatException ex) {
            appendLog("Valor inválido: " + s);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String s = javax.swing.JOptionPane.showInputDialog(
                this, "Gramas de cal (Ca(OH)2) a adicionar:",
                "Adicionar cal", javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        if (s == null) {
            return;
        }
        try {
            double gramas = Double.parseDouble(s.trim().replace(',', '.'));
            if (gramas <= 0) {
                appendLog("Tentativa de adicionar cal inválida: " + s);
                return;
            }
            tcpClient.writeMessage("ADD_LIME|"
                    + String.format(java.util.Locale.US, "%.3f", gramas) + "|");
            appendLog(String.format("%s Comando enviado: ADD_LIME %s g", timeNow(), df3.format(gramas)));
        } catch (NumberFormatException ex) {
            appendLog("Valor inválido: " + s);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void fazerEleicao() {
        System.out.println("Iniciando eleição...");
        this.emEleicao = true;
        boolean sentToHigher = false;

        synchronized (clientesAtivos) {
            for (int id : clientesAtivos) {
                if (id > this.myId) {
                    tcpClient.writeMessage("ELECTION|" + this.myId + "|");
                    sentToHigher = true;
                    break;
                }
            }
        }

        if (!sentToHigher) {
            System.out.println("Ninguém maior que eu. Eu sou o novo coordenador.");
            this.coordinatorId = this.myId;
            this.emEleicao = false;
            tcpClient.writeMessage("COORDINATOR|" + this.myId + "|");
        }
    }

    public void atualizarListaCliente(List<Integer> ids) {
        synchronized (clientesAtivos) {
            clientesAtivos.clear();
            clientesAtivos.addAll(ids);
        }
        System.out.println("Clientes ativos: " + ids);
    }

    public void receberEleicaoInfo(int senderId) {
        if (senderId < this.myId) {
            System.out.println("Recebi ELECTION de " + senderId + ". Respondendo ALIVE.");
            tcpClient.writeMessage("ALIVE|" + this.myId + "|");

            if (!this.emEleicao) {
                fazerEleicao();
            }
        }
    }

    public void receberAlive(int senderId) {
        if (this.emEleicao && senderId > this.myId) {
            System.out.println("Recebi ALIVE de " + senderId + ". Perdi a eleição.");
            this.emEleicao = false;
        }
    }

    public void recebeMensagemCoord(int winnerId) {
        System.out.println("Novo coordenador é: " + winnerId);
        this.coordinatorId = winnerId;
        this.emEleicao = false;

        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jLabel4.setText(myId == winnerId ? "ADM" : "User");
                jLabel6.setText(winnerId >= 0 ? ("Coordenador: " + winnerId) : "Coordenador: Nenhum");
                jButton4.setEnabled(myId == winnerId ? true : false);
                jButton5.setEnabled(myId == winnerId ? true : false);
            }
        });
    }

    public void recebePingServer(long ts, int coordId) {
        if (this.myId == coordId && this.myId == this.coordinatorId) {
            tcpClient.writeMessage("PONG|" + this.myId + "|" + ts + "|");
        }
    }

    public void onServerTriggerElection() {
        int minId = this.myId;
        synchronized (clientesAtivos) {
            for (int id : clientesAtivos) {
                if (id < minId) {
                    minId = id;
                }
            }
        }
        if (this.myId == minId) {
            fazerEleicao();
        } else {
            System.out.println("TRIGGER_ELECTION recebido. Menor ID é " + minId + ". Aguardando ele iniciar.");
        }
    }

    public void closeConnection() {
        try {
            tcpClient.closeConnection();
            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
            jTextField3.setEditable(true);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateLEDsAndMaybeLog(boolean phRedNow, boolean tempRedNow) {
        if (phRedNow != ledPHRed) {
            if (phRedNow) {
                appendLog(String.format("%s ALERTA: pH fora da faixa segura (vermelho). pH=%s", timeNow(), df3.format(pH)));
            } else {
                appendLog(String.format("%s pH saiu da faixa vermelha. pH=%s", timeNow(), df3.format(pH)));
            }
        }
        ledPHRed = phRedNow;

        if (tempRedNow != ledTempRed) {
            if (tempRedNow) {
                appendLog(String.format("%s ALERTA: Temperatura fora da faixa segura (vermelho). Temp=%s °C", timeNow(), df1.format(temperaturaC)));
            } else {
                appendLog(String.format("%s Temperatura saiu da faixa vermelha. Temp=%s °C", timeNow(), df1.format(temperaturaC)));
            }
        }
        ledTempRed = tempRedNow;
    }

    private void updateUIValues() {
        javax.swing.SwingUtilities.invokeLater(() -> {
            lblVolumeVal.setText("Mosto:  " + df3.format(volumeL) + " L");
            lblPHVal.setText("PH:  " + df3.format(pH));
            lblTempVal.setText("TEMP: " + df1.format(temperaturaC) + " °C");

            if (checkPHGreen(pH)) {
                setLedColor(ledPH, java.awt.Color.GREEN);
            } else if (checkPHYellow(pH)) {
                setLedColor(ledPH, java.awt.Color.YELLOW);
            } else {
                setLedColor(ledPH, java.awt.Color.RED);
            }

            if (checkTempGreen(temperaturaC)) {
                setLedColor(ledTemp, java.awt.Color.GREEN);
            } else if (checkTempYellow(temperaturaC)) {
                setLedColor(ledTemp, java.awt.Color.YELLOW);
            } else {
                setLedColor(ledTemp, java.awt.Color.RED);
            }

            contadorLabel.setText("Contador: " + riscoCounter + " s");
        });
    }

    public void updateServerState(double volume, double newPH, double temp) {
        this.volumeL = volume;
        this.pH = newPH;
        this.temperaturaC = temp;
        updateUIValues();
    }

    private void setLedColor(JPanel ledPanel, Color color) {
        Graphics g = ledPanel.getGraphics();
        if (g != null) {
            g.setColor(color);
            g.fillOval(0, 0, ledPanel.getWidth() - 1, ledPanel.getHeight() - 1);
            g.setColor(Color.DARK_GRAY.darker());
            g.drawOval(0, 0, ledPanel.getWidth() - 1, ledPanel.getHeight() - 1);
            g.dispose();
        } else {
            ledPanel.repaint();
        }
    }

    private boolean checkTempRed(double tempC) {
        return (tempC < 20.0) || (tempC > 45.0);
    }

    private boolean checkTempYellow(double tempC) {
        return (tempC >= 20.0 && tempC < 25.0) || (tempC > 35.0 && tempC <= 45.0);
    }

    private boolean checkTempGreen(double tempC) {
        return (tempC >= 25.0 && tempC <= 35.0);
    }

    private boolean checkPHRed(double phVal) {
        return (phVal < 3.8) || (phVal > 6.0);
    }

    private boolean checkPHYellow(double phVal) {
        return (phVal >= 3.8 && phVal < 4.5) || (phVal > 5.5 && phVal <= 6.0);
    }

    private boolean checkPHGreen(double phVal) {
        return (phVal >= 4.5 && phVal <= 5.5);
    }

    private void appendLog(String s) {
        SwingUtilities.invokeLater(() -> {
            logArea.append(s + "\n\n");
            logArea.setCaretPosition(logArea.getDocument().getLength());
        });
    }

    private String timeNow() {
        return LocalTime.now().withNano(0).toString();
    }

    public void onServerError(String code, String detail) {
        SwingUtilities.invokeLater(() -> {
            String msg;
            switch (code) {
                case "DUPLICATE_ID":
                    msg = (detail != null && !detail.isEmpty())
                            ? detail
                            : "ID já está em uso neste servidor. Escolha outro ID.";
                    break;
                default:
                    msg = "Erro do servidor: " + code;
                    if (detail != null && !detail.isEmpty()) {
                        msg += " — " + detail;
                    }
            }

            JOptionPane.showMessageDialog(
                    this, msg, "ERRO", JOptionPane.ERROR_MESSAGE
            );

            jButton1.setEnabled(true);
            jButton2.setEnabled(false);
            jTextField3.setEditable(true);
            jLabel4.setText("User");
            jLabel6.setText("Coordenador: Nenhum");
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
        });

        try {
            if (tcpClient != null) {
                tcpClient.closeConnection();
            }
        } catch (IOException ignore) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BullyClient1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contadorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblPHVal;
    private javax.swing.JLabel lblTempVal;
    private javax.swing.JLabel lblVolumeVal;
    private javax.swing.JPanel ledPH;
    private javax.swing.JPanel ledTemp;
    private javax.swing.JTextArea logArea;
    // End of variables declaration//GEN-END:variables
    private Bully_TCPClientMain tcpClient;
}
